name: Terraform Plan (Feature Branch)

on:
  push:
    branches:
      - feature1 # ← अपनी feature branch का नाम डालो
  pull_request:
    branches:
      - main

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      # 3. Azure Login (hardcoded creds - testing only)
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "68462574-574a-4446-a2e0-85187be1e52c",
              "clientSecret": "Eho8Q~A4w_ehNh5J2jH_-bHYutEqtKbHoyZlzbRB",
              "subscriptionId": "42a164d5-8e3e-4b00-9cd7-14e58100c64d",
              "tenantId": "617a262c-d3a9-40d4-8b46-1d889f22b189"
            }

      # 4. Terraform Init
      - name: Terraform Init
        run: terraform init

      # 5. Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # 6. Terraform Plan
      - name: Terraform Plan
        run: terraform plan
